name: Compile iOS binaries

on:
  push:
    branches: [ master, NET10 ]
  pull_request:
    branches: [ master ]
  release:
     types: 
       - published
       - prereleased
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-arm64:
    runs-on: macos-26

    steps:
    - uses: actions/checkout@v6
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "26.5"

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json

    - name: Restore workloads
      run: dotnet workload restore GalaxyBudsClient.iOS/GalaxyBudsClient.iOS.csproj
    - name: Restore dependencies
      run: dotnet restore --configfile GalaxyBudsClient/nuget.config GalaxyBudsClient.iOS/GalaxyBudsClient.iOS.csproj -p:IsIos=true
    - name: Build iOS arm64 IPA
      run: dotnet publish -f net10.0-ios -r ios-arm64 -o bin_ios -c Release -p:BuildIpa=true -p:ArchiveOnBuild=true -p:EnableCodeSigning=false -p:IsIos=true --no-restore GalaxyBudsClient.iOS/GalaxyBudsClient.iOS.csproj

    - name: Upload artifacts
      uses: actions/upload-artifact@v6
      with:
        name: GalaxyBudsClient_ios-arm64
        path: bin_ios/**/*.ipa
        if-no-files-found: error

  attach-to-release:
    runs-on: ubuntu-latest
    needs: [build-arm64]
    if: github.event_name == 'release'
    permissions:
      contents: write

    steps:
    - name: Download setup artifact (arm64)
      uses: actions/download-artifact@v7
      with:
        name: GalaxyBudsClient_ios-arm64

    - name: Rename (arm64)
      run: |
        file="$(find . -maxdepth 1 -name '*.ipa' | head -n1)"
        mv "$file" GalaxyBudsClient_iOS_arm64.ipa

    - uses: AButler/upload-release-assets@v3.0.1
      with:
        files: '*.ipa'
        repo-token: ${{ secrets.GH_TOKEN }}
